# Generated by Django 5.0 on 2024-01-16 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_subadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.PositiveSmallIntegerField()),
                ('pic', models.ImageField(upload_to='RestUsers/Profile_Pics/')),
                ('resume', models.FileField(upload_to='RestUsers/Resumes/')),
                ('approved', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('receptionist', 'receptionist'), ('barer', 'barer'), ('chef', 'chef')], max_length=100)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_RestUsers',
            },
        ),
    ]
