# Generated by Django 4.2.5 on 2023-12-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='', verbose_name='Restaurant_Pics/')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
    ]
