# Generated by Django 4.2.5 on 2023-12-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='django_Restaurant',
        ),
    ]
