# Generated by Django 4.2.5 on 2023-12-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pic',
            field=models.ImageField(upload_to='Restaurant_Pics/'),
        ),
    ]
