# Generated by Django 4.2.5 on 2023-12-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAdmin',
        ),
    ]
