# Generated by Django 4.2.5 on 2023-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customertableorders_table_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertableorders',
            name='food',
        ),
        migrations.AddField(
            model_name='customertableorders',
            name='food_ids',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customertableorders',
            name='food_quantities',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
