# Generated by Django 4.2.5 on 2023-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customertableorders_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfoodorders',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='customerfoodorders',
            name='food',
        ),
        migrations.RemoveField(
            model_name='customerfoodorders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='customerfoodorders',
            name='food_ids',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfoodorders',
            name='food_quantities',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
