# Generated by Django 4.2.5 on 2023-12-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
                ('pic', models.ImageField(upload_to='Food_Pics/')),
                ('price', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_food',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('seater', models.PositiveSmallIntegerField()),
                ('pic', models.ImageField(upload_to='Table_Pics/')),
            ],
            options={
                'db_table': 'django_table',
            },
        ),
    ]
